name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - scikit-learn=1.6.1
  - pip
  - pip:
    - mlflow==2.19.0 # Pindahkan mlflow ke instalasi pip untuk memastikan
    - gunicorn
    - matplotlib # Tambahkan kembali matplotlib dan seaborn jika ingin tercatat di requirements.txt MLflow
    - seaborn
