name: CI Workflow - MLflow Model Training

on:
  push:
    branches:
      - main # Trigger workflow setiap kali ada push ke branch 'main'
  workflow_dispatch: # Memungkinkan trigger manual dari GitHub UI

jobs:
  train_model:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Mengunduh kode repository Anda

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: mlflow-env # Nama environment dari conda.yaml
        python-version: 3.11 # Sesuaikan dengan versi python Anda (berdasarkan python3.11.12)
        auto-activate-base: false # Penting: Jangan aktifkan base env

    - name: Install MLflow (Explicitly via pip)
      shell: bash -l {0}
      run: |
        conda activate mlflow-env # Pastikan environment aktif
        pip install mlflow==2.19.0 # Instal MLflow secara eksplisit

    - name: Verify Conda Environment Setup (Post-Installation)
      shell: bash -l {0}
      run: |
        echo "Conda Info:"
        conda info
        echo "Conda List in environment:"
        conda list
        echo "Pip Freeze in environment:"
        pip freeze # Ini akan menunjukkan paket pip yang terinstal di env Conda

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject # Pastikan berada di direktori MLProject
        # Memanggil mlflow sebagai modul python via conda run untuk keandalan
        conda run -n mlflow-env python -m mlflow run .

    - name: List MLflow Artifacts (Optional for Debugging)
      shell: bash -l {0}
      run: |
        # Path ini harus relatif dari root repo, karena mlruns dibuat di dalam MLProject
        echo "Listing MLflow Artifacts:"
        ls -R MLProject/mlruns/
