name: CI Workflow - MLflow Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: mlflow-env
        python-version: 3.11
        auto-activate-base: false

    - name: Install MLflow (Explicitly via pip) # Langkah baru untuk instalasi MLflow
      shell: bash -l {0}
      run: |
        conda activate mlflow-env # Pastikan environment aktif
        pip install mlflow==2.19.0 # Instal MLflow secara eksplisit

    - name: Verify Conda Environment Setup (Post-Installation)
      shell: bash -l {0}
      run: |
        echo "Conda Info:"
        conda info
        echo "Conda List in environment:"
        conda list
        echo "Pip Freeze in environment:"
        pip freeze

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        conda run -n mlflow-env python -m mlflow run .

    - name: List MLflow Artifacts (Optional for Debugging)
      shell: bash -l {0}
      run: |
        echo "Listing MLflow Artifacts:"
        ls -R /home/runner/work/Workflow-CI/Workflow-CI/mlruns/
