name: CI Workflow - MLflow Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: mlflow-env
        python-version: 3.11 # Sesuaikan dengan versi python di conda.yaml
        auto-activate-base: false

    # Penting: Tambahkan shell: bash -l {0} atau shell: bash -l
    # Ini memastikan shell adalah login shell, sehingga conda bisa diinisialisasi
    - name: Verify Conda Environment Setup
      # Ubah baris berikut
      shell: bash -l {0} # Penting: Gunakan login shell
      run: |
        conda info
        conda activate mlflow-env # Baris ini mungkin tidak lagi perlu jika sudah auto-activate
        conda list

    - name: Run MLflow Project
      # Ubah baris berikut
      shell: bash -l {0} # Penting: Gunakan login shell
      run: |
        conda activate mlflow-env # Pastikan environment aktif
        cd MLProject
        mlflow run .

    - name: List MLflow Artifacts (Optional for Debugging)
      shell: bash -l {0} # Juga gunakan login shell
      run: |
        ls -R /home/runner/work/Workflow-CI/Workflow-CI/mlruns/
