name: CI Workflow - MLflow Model Training

on:
  push:
    branches:
      - main # Trigger workflow setiap kali ada push ke branch 'main'
  workflow_dispatch: # Memungkinkan trigger manual dari GitHub UI

jobs:
  train_model:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Mengunduh kode repository Anda

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: mlflow-env # Nama environment dari conda.yaml
        python-version: 3.11 # Sesuaikan dengan versi python di conda.yaml (berdasarkan python3.11.12 Anda)
        auto-activate-base: false # Penting: Jangan aktifkan base env

    - name: Verify Conda Environment Setup
      shell: bash -l {0} # Penting: Gunakan login shell
      run: |
        echo "Conda Info:"
        conda info
        echo "Conda List:"
        conda list

    - name: Run MLflow Project
      shell: bash -l {0} # Penting: Gunakan login shell
      run: |
        cd MLProject # Pastikan berada di direktori MLProject
        # Memanggil mlflow sebagai modul python via conda run untuk keandalan
        conda run -n mlflow-env python -m mlflow run .

    - name: List MLflow Artifacts (Optional for Debugging)
      shell: bash -l {0}
      run: |
        # Lokasi default mlruns di GitHub Actions runner: /home/runner/work/<repo_name>/<repo_name>/mlruns/
        # Ganti <repo_name> dengan Workflow-CI
        echo "Listing MLflow Artifacts:"
        ls -R /home/runner/work/Workflow-CI/Workflow-CI/mlruns/
